version: '2'
services:
  ruby:
    image: ruby:3.2-alpine@sha256:2689717977dd07ddc14b943b821f15662ee1005b087d61ab932d1a85f3fb01d5
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"