version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:v3.0.1
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:3.1-alpine@sha256:0b91e98c4613c2287bb7274a1584ea141b68960fb6b0edd7fe32127dc888d1a0
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"