version: '2'
services:
  ruby:
    image: ruby:3.2-alpine@sha256:198e97ccb12cd0297c274d10e504138f412f90bed50c36ebde0a466ab89cf526
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"