version: '2'
services:
  ruby:
    image: ruby:3.1-alpine@sha256:a39e26d0598837f08c75a42c8b0886d9ed5cc862c4b535662922ee1d05272fca
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"