version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:0373d59706f995ef31c528c3962b2c27481eeaeb87f90caca8aba16e7ecbac8f
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"